*
fatal: [172.16.1.2]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'gid'\n\nThe error appears to have been in '/home/ansible/sato/addgrouptest/addgrouptest.yml': line 14, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: addusers\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'gid'"}
fatal: [172.16.1.3]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'gid'\n\nThe error appears to have been in '/home/ansible/sato/addgrouptest/addgrouptest.yml': line 14, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: addusers\n      ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'dict object' has no attribute 'gid'"}
        to retry, use: --limit @/home/ansible/sato/addgrouptest/addgrouptest.retry

